/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticalsIndexRouteImport } from './routes/_app.analyticals.index'
import { Route as AppAnalyticalsIdRouteImport } from './routes/_app.analyticals.$id'
import { Route as AppAnalyticalsNewRouteImport } from './routes/_app.analyticals.new'
import { Route as AppBillsIndexRouteImport } from './routes/_app.bills.index'
import { Route as AppBillsNewRouteImport } from './routes/_app.bills.new'
import { Route as AppBrandsIndexRouteImport } from './routes/_app.brands.index'
import { Route as AppBrandsNewRouteImport } from './routes/_app.brands.new'
import { Route as AppBudgetsIndexRouteImport } from './routes/_app.budgets.index'
import { Route as AppBudgetsIdRouteImport } from './routes/_app.budgets.$id'
import { Route as AppBudgetsNewRouteImport } from './routes/_app.budgets.new'
import { Route as AppCategoriesIndexRouteImport } from './routes/_app.categories.index'
import { Route as AppChartOfAccountsIndexRouteImport } from './routes/_app.chart-of-accounts.index'
import { Route as AppChartOfAccountsNewRouteImport } from './routes/_app.chart-of-accounts.new'
import { Route as AppContactsIndexRouteImport } from './routes/_app.contacts.index'
import { Route as AppContactsIdRouteImport } from './routes/_app.contacts.$id'
import { Route as AppContactsNewRouteImport } from './routes/_app.contacts.new'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app.invoices.index'
import { Route as AppInvoicesNewRouteImport } from './routes/_app.invoices.new'
import { Route as AppJournalEntriesIndexRouteImport } from './routes/_app.journal-entries.index'
import { Route as AppJournalEntriesNewRouteImport } from './routes/_app.journal-entries.new'
import { Route as AppJournalsIndexRouteImport } from './routes/_app.journals.index'
import { Route as AppJournalsNewRouteImport } from './routes/_app.journals.new'
import { Route as AppPaymentsIndexRouteImport } from './routes/_app.payments.index'
import { Route as AppProductsIndexRouteImport } from './routes/_app.products.index'
import { Route as AppProductsIdRouteImport } from './routes/_app.products.$id'
import { Route as AppProductsNewRouteImport } from './routes/_app.products.new'
import { Route as AppPurchaseOrdersIndexRouteImport } from './routes/_app.purchase-orders.index'
import { Route as AppPurchaseOrdersIdRouteImport } from './routes/_app.purchase-orders.$id'
import { Route as AppPurchaseOrdersNewRouteImport } from './routes/_app.purchase-orders.new'
import { Route as AppReportsBalanceSheetRouteImport } from './routes/_app.reports.balance-sheet'
import { Route as AppReportsBudgetReportRouteImport } from './routes/_app.reports.budget-report'
import { Route as AppReportsProfitAndLossRouteImport } from './routes/_app.reports.profit-and-loss'
import { Route as AppSalesOrdersIndexRouteImport } from './routes/_app.sales-orders.index'
import { Route as AppSalesOrdersIdRouteImport } from './routes/_app.sales-orders.$id'
import { Route as AppSalesOrdersNewRouteImport } from './routes/_app.sales-orders.new'
import { Route as AppUsersIndexRouteImport } from './routes/_app.users.index'
import { Route as AppUsersNewRouteImport } from './routes/_app.users.new'
import { Route as AppBillsIdIndexRouteImport } from './routes/_app.bills.$id.index'
import { Route as AppBillsIdPayRouteImport } from './routes/_app.bills.$id.pay'
import { Route as AppInvoicesIdIndexRouteImport } from './routes/_app.invoices.$id.index'
import { Route as AppInvoicesIdPayRouteImport } from './routes/_app.invoices.$id.pay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticalsIndexRoute = AppAnalyticalsIndexRouteImport.update({
  id: '/analyticals/',
  path: '/analyticals/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticalsIdRoute = AppAnalyticalsIdRouteImport.update({
  id: '/analyticals/$id',
  path: '/analyticals/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticalsNewRoute = AppAnalyticalsNewRouteImport.update({
  id: '/analyticals/new',
  path: '/analyticals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIndexRoute = AppBillsIndexRouteImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsNewRoute = AppBillsNewRouteImport.update({
  id: '/bills/new',
  path: '/bills/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsIndexRoute = AppBrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsNewRoute = AppBrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIndexRoute = AppBudgetsIndexRouteImport.update({
  id: '/budgets/',
  path: '/budgets/',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsIdRoute = AppBudgetsIdRouteImport.update({
  id: '/budgets/$id',
  path: '/budgets/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppBudgetsNewRoute = AppBudgetsNewRouteImport.update({
  id: '/budgets/new',
  path: '/budgets/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesIndexRoute = AppCategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => AppRoute,
} as any)
const AppChartOfAccountsIndexRoute = AppChartOfAccountsIndexRouteImport.update({
  id: '/chart-of-accounts/',
  path: '/chart-of-accounts/',
  getParentRoute: () => AppRoute,
} as any)
const AppChartOfAccountsNewRoute = AppChartOfAccountsNewRouteImport.update({
  id: '/chart-of-accounts/new',
  path: '/chart-of-accounts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIndexRoute = AppContactsIndexRouteImport.update({
  id: '/contacts/',
  path: '/contacts/',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsIdRoute = AppContactsIdRouteImport.update({
  id: '/contacts/$id',
  path: '/contacts/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsNewRoute = AppContactsNewRouteImport.update({
  id: '/contacts/new',
  path: '/contacts/new',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesNewRoute = AppInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalEntriesIndexRoute = AppJournalEntriesIndexRouteImport.update({
  id: '/journal-entries/',
  path: '/journal-entries/',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalEntriesNewRoute = AppJournalEntriesNewRouteImport.update({
  id: '/journal-entries/new',
  path: '/journal-entries/new',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalsIndexRoute = AppJournalsIndexRouteImport.update({
  id: '/journals/',
  path: '/journals/',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalsNewRoute = AppJournalsNewRouteImport.update({
  id: '/journals/new',
  path: '/journals/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPaymentsIndexRoute = AppPaymentsIndexRouteImport.update({
  id: '/payments/',
  path: '/payments/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsNewRoute = AppProductsNewRouteImport.update({
  id: '/products/new',
  path: '/products/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIndexRoute = AppPurchaseOrdersIndexRouteImport.update({
  id: '/purchase-orders/',
  path: '/purchase-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersIdRoute = AppPurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppPurchaseOrdersNewRoute = AppPurchaseOrdersNewRouteImport.update({
  id: '/purchase-orders/new',
  path: '/purchase-orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBalanceSheetRoute = AppReportsBalanceSheetRouteImport.update({
  id: '/reports/balance-sheet',
  path: '/reports/balance-sheet',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsBudgetReportRoute = AppReportsBudgetReportRouteImport.update({
  id: '/reports/budget-report',
  path: '/reports/budget-report',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsProfitAndLossRoute = AppReportsProfitAndLossRouteImport.update({
  id: '/reports/profit-and-loss',
  path: '/reports/profit-and-loss',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIndexRoute = AppSalesOrdersIndexRouteImport.update({
  id: '/sales-orders/',
  path: '/sales-orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersIdRoute = AppSalesOrdersIdRouteImport.update({
  id: '/sales-orders/$id',
  path: '/sales-orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppSalesOrdersNewRoute = AppSalesOrdersNewRouteImport.update({
  id: '/sales-orders/new',
  path: '/sales-orders/new',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersNewRoute = AppUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIdIndexRoute = AppBillsIdIndexRouteImport.update({
  id: '/bills/$id/',
  path: '/bills/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppBillsIdPayRoute = AppBillsIdPayRouteImport.update({
  id: '/bills/$id/pay',
  path: '/bills/$id/pay',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdIndexRoute = AppInvoicesIdIndexRouteImport.update({
  id: '/invoices/$id/',
  path: '/invoices/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesIdPayRoute = AppInvoicesIdPayRouteImport.update({
  id: '/invoices/$id/pay',
  path: '/invoices/$id/pay',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/analyticals/$id': typeof AppAnalyticalsIdRoute
  '/analyticals/new': typeof AppAnalyticalsNewRoute
  '/bills/new': typeof AppBillsNewRoute
  '/brands/new': typeof AppBrandsNewRoute
  '/budgets/$id': typeof AppBudgetsIdRoute
  '/budgets/new': typeof AppBudgetsNewRoute
  '/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/journal-entries/new': typeof AppJournalEntriesNewRoute
  '/journals/new': typeof AppJournalsNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/budget-report': typeof AppReportsBudgetReportRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/sales-orders/new': typeof AppSalesOrdersNewRoute
  '/users/new': typeof AppUsersNewRoute
  '/analyticals/': typeof AppAnalyticalsIndexRoute
  '/bills/': typeof AppBillsIndexRoute
  '/brands/': typeof AppBrandsIndexRoute
  '/budgets/': typeof AppBudgetsIndexRoute
  '/categories/': typeof AppCategoriesIndexRoute
  '/chart-of-accounts/': typeof AppChartOfAccountsIndexRoute
  '/contacts/': typeof AppContactsIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/journal-entries/': typeof AppJournalEntriesIndexRoute
  '/journals/': typeof AppJournalsIndexRoute
  '/payments/': typeof AppPaymentsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/bills/$id/pay': typeof AppBillsIdPayRoute
  '/invoices/$id/pay': typeof AppInvoicesIdPayRoute
  '/bills/$id/': typeof AppBillsIdIndexRoute
  '/invoices/$id/': typeof AppInvoicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AppDashboardRoute
  '/analyticals/$id': typeof AppAnalyticalsIdRoute
  '/analyticals/new': typeof AppAnalyticalsNewRoute
  '/bills/new': typeof AppBillsNewRoute
  '/brands/new': typeof AppBrandsNewRoute
  '/budgets/$id': typeof AppBudgetsIdRoute
  '/budgets/new': typeof AppBudgetsNewRoute
  '/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/contacts/$id': typeof AppContactsIdRoute
  '/contacts/new': typeof AppContactsNewRoute
  '/invoices/new': typeof AppInvoicesNewRoute
  '/journal-entries/new': typeof AppJournalEntriesNewRoute
  '/journals/new': typeof AppJournalsNewRoute
  '/products/$id': typeof AppProductsIdRoute
  '/products/new': typeof AppProductsNewRoute
  '/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/reports/budget-report': typeof AppReportsBudgetReportRoute
  '/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/sales-orders/new': typeof AppSalesOrdersNewRoute
  '/users/new': typeof AppUsersNewRoute
  '/analyticals': typeof AppAnalyticalsIndexRoute
  '/bills': typeof AppBillsIndexRoute
  '/brands': typeof AppBrandsIndexRoute
  '/budgets': typeof AppBudgetsIndexRoute
  '/categories': typeof AppCategoriesIndexRoute
  '/chart-of-accounts': typeof AppChartOfAccountsIndexRoute
  '/contacts': typeof AppContactsIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/journal-entries': typeof AppJournalEntriesIndexRoute
  '/journals': typeof AppJournalsIndexRoute
  '/payments': typeof AppPaymentsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/purchase-orders': typeof AppPurchaseOrdersIndexRoute
  '/sales-orders': typeof AppSalesOrdersIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/bills/$id/pay': typeof AppBillsIdPayRoute
  '/invoices/$id/pay': typeof AppInvoicesIdPayRoute
  '/bills/$id': typeof AppBillsIdIndexRoute
  '/invoices/$id': typeof AppInvoicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/analyticals/$id': typeof AppAnalyticalsIdRoute
  '/_app/analyticals/new': typeof AppAnalyticalsNewRoute
  '/_app/bills/new': typeof AppBillsNewRoute
  '/_app/brands/new': typeof AppBrandsNewRoute
  '/_app/budgets/$id': typeof AppBudgetsIdRoute
  '/_app/budgets/new': typeof AppBudgetsNewRoute
  '/_app/chart-of-accounts/new': typeof AppChartOfAccountsNewRoute
  '/_app/contacts/$id': typeof AppContactsIdRoute
  '/_app/contacts/new': typeof AppContactsNewRoute
  '/_app/invoices/new': typeof AppInvoicesNewRoute
  '/_app/journal-entries/new': typeof AppJournalEntriesNewRoute
  '/_app/journals/new': typeof AppJournalsNewRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/products/new': typeof AppProductsNewRoute
  '/_app/purchase-orders/$id': typeof AppPurchaseOrdersIdRoute
  '/_app/purchase-orders/new': typeof AppPurchaseOrdersNewRoute
  '/_app/reports/balance-sheet': typeof AppReportsBalanceSheetRoute
  '/_app/reports/budget-report': typeof AppReportsBudgetReportRoute
  '/_app/reports/profit-and-loss': typeof AppReportsProfitAndLossRoute
  '/_app/sales-orders/$id': typeof AppSalesOrdersIdRoute
  '/_app/sales-orders/new': typeof AppSalesOrdersNewRoute
  '/_app/users/new': typeof AppUsersNewRoute
  '/_app/analyticals/': typeof AppAnalyticalsIndexRoute
  '/_app/bills/': typeof AppBillsIndexRoute
  '/_app/brands/': typeof AppBrandsIndexRoute
  '/_app/budgets/': typeof AppBudgetsIndexRoute
  '/_app/categories/': typeof AppCategoriesIndexRoute
  '/_app/chart-of-accounts/': typeof AppChartOfAccountsIndexRoute
  '/_app/contacts/': typeof AppContactsIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/journal-entries/': typeof AppJournalEntriesIndexRoute
  '/_app/journals/': typeof AppJournalsIndexRoute
  '/_app/payments/': typeof AppPaymentsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/purchase-orders/': typeof AppPurchaseOrdersIndexRoute
  '/_app/sales-orders/': typeof AppSalesOrdersIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_app/bills/$id/pay': typeof AppBillsIdPayRoute
  '/_app/invoices/$id/pay': typeof AppInvoicesIdPayRoute
  '/_app/bills/$id/': typeof AppBillsIdIndexRoute
  '/_app/invoices/$id/': typeof AppInvoicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/analyticals/$id'
    | '/analyticals/new'
    | '/bills/new'
    | '/brands/new'
    | '/budgets/$id'
    | '/budgets/new'
    | '/chart-of-accounts/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/invoices/new'
    | '/journal-entries/new'
    | '/journals/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/reports/balance-sheet'
    | '/reports/budget-report'
    | '/reports/profit-and-loss'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/users/new'
    | '/analyticals/'
    | '/bills/'
    | '/brands/'
    | '/budgets/'
    | '/categories/'
    | '/chart-of-accounts/'
    | '/contacts/'
    | '/invoices/'
    | '/journal-entries/'
    | '/journals/'
    | '/payments/'
    | '/products/'
    | '/purchase-orders/'
    | '/sales-orders/'
    | '/users/'
    | '/bills/$id/pay'
    | '/invoices/$id/pay'
    | '/bills/$id/'
    | '/invoices/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/analyticals/$id'
    | '/analyticals/new'
    | '/bills/new'
    | '/brands/new'
    | '/budgets/$id'
    | '/budgets/new'
    | '/chart-of-accounts/new'
    | '/contacts/$id'
    | '/contacts/new'
    | '/invoices/new'
    | '/journal-entries/new'
    | '/journals/new'
    | '/products/$id'
    | '/products/new'
    | '/purchase-orders/$id'
    | '/purchase-orders/new'
    | '/reports/balance-sheet'
    | '/reports/budget-report'
    | '/reports/profit-and-loss'
    | '/sales-orders/$id'
    | '/sales-orders/new'
    | '/users/new'
    | '/analyticals'
    | '/bills'
    | '/brands'
    | '/budgets'
    | '/categories'
    | '/chart-of-accounts'
    | '/contacts'
    | '/invoices'
    | '/journal-entries'
    | '/journals'
    | '/payments'
    | '/products'
    | '/purchase-orders'
    | '/sales-orders'
    | '/users'
    | '/bills/$id/pay'
    | '/invoices/$id/pay'
    | '/bills/$id'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_app/dashboard'
    | '/_app/analyticals/$id'
    | '/_app/analyticals/new'
    | '/_app/bills/new'
    | '/_app/brands/new'
    | '/_app/budgets/$id'
    | '/_app/budgets/new'
    | '/_app/chart-of-accounts/new'
    | '/_app/contacts/$id'
    | '/_app/contacts/new'
    | '/_app/invoices/new'
    | '/_app/journal-entries/new'
    | '/_app/journals/new'
    | '/_app/products/$id'
    | '/_app/products/new'
    | '/_app/purchase-orders/$id'
    | '/_app/purchase-orders/new'
    | '/_app/reports/balance-sheet'
    | '/_app/reports/budget-report'
    | '/_app/reports/profit-and-loss'
    | '/_app/sales-orders/$id'
    | '/_app/sales-orders/new'
    | '/_app/users/new'
    | '/_app/analyticals/'
    | '/_app/bills/'
    | '/_app/brands/'
    | '/_app/budgets/'
    | '/_app/categories/'
    | '/_app/chart-of-accounts/'
    | '/_app/contacts/'
    | '/_app/invoices/'
    | '/_app/journal-entries/'
    | '/_app/journals/'
    | '/_app/payments/'
    | '/_app/products/'
    | '/_app/purchase-orders/'
    | '/_app/sales-orders/'
    | '/_app/users/'
    | '/_app/bills/$id/pay'
    | '/_app/invoices/$id/pay'
    | '/_app/bills/$id/'
    | '/_app/invoices/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyticals/': {
      id: '/_app/analyticals/'
      path: '/analyticals'
      fullPath: '/analyticals/'
      preLoaderRoute: typeof AppAnalyticalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyticals/$id': {
      id: '/_app/analyticals/$id'
      path: '/analyticals/$id'
      fullPath: '/analyticals/$id'
      preLoaderRoute: typeof AppAnalyticalsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analyticals/new': {
      id: '/_app/analyticals/new'
      path: '/analyticals/new'
      fullPath: '/analyticals/new'
      preLoaderRoute: typeof AppAnalyticalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/': {
      id: '/_app/bills/'
      path: '/bills'
      fullPath: '/bills/'
      preLoaderRoute: typeof AppBillsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/new': {
      id: '/_app/bills/new'
      path: '/bills/new'
      fullPath: '/bills/new'
      preLoaderRoute: typeof AppBillsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/': {
      id: '/_app/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof AppBrandsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands/new': {
      id: '/_app/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof AppBrandsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/': {
      id: '/_app/budgets/'
      path: '/budgets'
      fullPath: '/budgets/'
      preLoaderRoute: typeof AppBudgetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/$id': {
      id: '/_app/budgets/$id'
      path: '/budgets/$id'
      fullPath: '/budgets/$id'
      preLoaderRoute: typeof AppBudgetsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/budgets/new': {
      id: '/_app/budgets/new'
      path: '/budgets/new'
      fullPath: '/budgets/new'
      preLoaderRoute: typeof AppBudgetsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories/': {
      id: '/_app/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof AppCategoriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart-of-accounts/': {
      id: '/_app/chart-of-accounts/'
      path: '/chart-of-accounts'
      fullPath: '/chart-of-accounts/'
      preLoaderRoute: typeof AppChartOfAccountsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chart-of-accounts/new': {
      id: '/_app/chart-of-accounts/new'
      path: '/chart-of-accounts/new'
      fullPath: '/chart-of-accounts/new'
      preLoaderRoute: typeof AppChartOfAccountsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/': {
      id: '/_app/contacts/'
      path: '/contacts'
      fullPath: '/contacts/'
      preLoaderRoute: typeof AppContactsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/$id': {
      id: '/_app/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof AppContactsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts/new': {
      id: '/_app/contacts/new'
      path: '/contacts/new'
      fullPath: '/contacts/new'
      preLoaderRoute: typeof AppContactsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/new': {
      id: '/_app/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AppInvoicesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal-entries/': {
      id: '/_app/journal-entries/'
      path: '/journal-entries'
      fullPath: '/journal-entries/'
      preLoaderRoute: typeof AppJournalEntriesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal-entries/new': {
      id: '/_app/journal-entries/new'
      path: '/journal-entries/new'
      fullPath: '/journal-entries/new'
      preLoaderRoute: typeof AppJournalEntriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journals/': {
      id: '/_app/journals/'
      path: '/journals'
      fullPath: '/journals/'
      preLoaderRoute: typeof AppJournalsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journals/new': {
      id: '/_app/journals/new'
      path: '/journals/new'
      fullPath: '/journals/new'
      preLoaderRoute: typeof AppJournalsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payments/': {
      id: '/_app/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AppPaymentsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/new': {
      id: '/_app/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AppProductsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/': {
      id: '/_app/purchase-orders/'
      path: '/purchase-orders'
      fullPath: '/purchase-orders/'
      preLoaderRoute: typeof AppPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/$id': {
      id: '/_app/purchase-orders/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof AppPurchaseOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/purchase-orders/new': {
      id: '/_app/purchase-orders/new'
      path: '/purchase-orders/new'
      fullPath: '/purchase-orders/new'
      preLoaderRoute: typeof AppPurchaseOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/balance-sheet': {
      id: '/_app/reports/balance-sheet'
      path: '/reports/balance-sheet'
      fullPath: '/reports/balance-sheet'
      preLoaderRoute: typeof AppReportsBalanceSheetRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/budget-report': {
      id: '/_app/reports/budget-report'
      path: '/reports/budget-report'
      fullPath: '/reports/budget-report'
      preLoaderRoute: typeof AppReportsBudgetReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/profit-and-loss': {
      id: '/_app/reports/profit-and-loss'
      path: '/reports/profit-and-loss'
      fullPath: '/reports/profit-and-loss'
      preLoaderRoute: typeof AppReportsProfitAndLossRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/': {
      id: '/_app/sales-orders/'
      path: '/sales-orders'
      fullPath: '/sales-orders/'
      preLoaderRoute: typeof AppSalesOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/$id': {
      id: '/_app/sales-orders/$id'
      path: '/sales-orders/$id'
      fullPath: '/sales-orders/$id'
      preLoaderRoute: typeof AppSalesOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sales-orders/new': {
      id: '/_app/sales-orders/new'
      path: '/sales-orders/new'
      fullPath: '/sales-orders/new'
      preLoaderRoute: typeof AppSalesOrdersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/new': {
      id: '/_app/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AppUsersNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/$id/': {
      id: '/_app/bills/$id/'
      path: '/bills/$id'
      fullPath: '/bills/$id/'
      preLoaderRoute: typeof AppBillsIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bills/$id/pay': {
      id: '/_app/bills/$id/pay'
      path: '/bills/$id/pay'
      fullPath: '/bills/$id/pay'
      preLoaderRoute: typeof AppBillsIdPayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id/': {
      id: '/_app/invoices/$id/'
      path: '/invoices/$id'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof AppInvoicesIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices/$id/pay': {
      id: '/_app/invoices/$id/pay'
      path: '/invoices/$id/pay'
      fullPath: '/invoices/$id/pay'
      preLoaderRoute: typeof AppInvoicesIdPayRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppAnalyticalsIdRoute: typeof AppAnalyticalsIdRoute
  AppAnalyticalsNewRoute: typeof AppAnalyticalsNewRoute
  AppBillsNewRoute: typeof AppBillsNewRoute
  AppBrandsNewRoute: typeof AppBrandsNewRoute
  AppBudgetsIdRoute: typeof AppBudgetsIdRoute
  AppBudgetsNewRoute: typeof AppBudgetsNewRoute
  AppChartOfAccountsNewRoute: typeof AppChartOfAccountsNewRoute
  AppContactsIdRoute: typeof AppContactsIdRoute
  AppContactsNewRoute: typeof AppContactsNewRoute
  AppInvoicesNewRoute: typeof AppInvoicesNewRoute
  AppJournalEntriesNewRoute: typeof AppJournalEntriesNewRoute
  AppJournalsNewRoute: typeof AppJournalsNewRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppProductsNewRoute: typeof AppProductsNewRoute
  AppPurchaseOrdersIdRoute: typeof AppPurchaseOrdersIdRoute
  AppPurchaseOrdersNewRoute: typeof AppPurchaseOrdersNewRoute
  AppReportsBalanceSheetRoute: typeof AppReportsBalanceSheetRoute
  AppReportsBudgetReportRoute: typeof AppReportsBudgetReportRoute
  AppReportsProfitAndLossRoute: typeof AppReportsProfitAndLossRoute
  AppSalesOrdersIdRoute: typeof AppSalesOrdersIdRoute
  AppSalesOrdersNewRoute: typeof AppSalesOrdersNewRoute
  AppUsersNewRoute: typeof AppUsersNewRoute
  AppAnalyticalsIndexRoute: typeof AppAnalyticalsIndexRoute
  AppBillsIndexRoute: typeof AppBillsIndexRoute
  AppBrandsIndexRoute: typeof AppBrandsIndexRoute
  AppBudgetsIndexRoute: typeof AppBudgetsIndexRoute
  AppCategoriesIndexRoute: typeof AppCategoriesIndexRoute
  AppChartOfAccountsIndexRoute: typeof AppChartOfAccountsIndexRoute
  AppContactsIndexRoute: typeof AppContactsIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppJournalEntriesIndexRoute: typeof AppJournalEntriesIndexRoute
  AppJournalsIndexRoute: typeof AppJournalsIndexRoute
  AppPaymentsIndexRoute: typeof AppPaymentsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppPurchaseOrdersIndexRoute: typeof AppPurchaseOrdersIndexRoute
  AppSalesOrdersIndexRoute: typeof AppSalesOrdersIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
  AppBillsIdPayRoute: typeof AppBillsIdPayRoute
  AppInvoicesIdPayRoute: typeof AppInvoicesIdPayRoute
  AppBillsIdIndexRoute: typeof AppBillsIdIndexRoute
  AppInvoicesIdIndexRoute: typeof AppInvoicesIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppAnalyticalsIdRoute: AppAnalyticalsIdRoute,
  AppAnalyticalsNewRoute: AppAnalyticalsNewRoute,
  AppBillsNewRoute: AppBillsNewRoute,
  AppBrandsNewRoute: AppBrandsNewRoute,
  AppBudgetsIdRoute: AppBudgetsIdRoute,
  AppBudgetsNewRoute: AppBudgetsNewRoute,
  AppChartOfAccountsNewRoute: AppChartOfAccountsNewRoute,
  AppContactsIdRoute: AppContactsIdRoute,
  AppContactsNewRoute: AppContactsNewRoute,
  AppInvoicesNewRoute: AppInvoicesNewRoute,
  AppJournalEntriesNewRoute: AppJournalEntriesNewRoute,
  AppJournalsNewRoute: AppJournalsNewRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppProductsNewRoute: AppProductsNewRoute,
  AppPurchaseOrdersIdRoute: AppPurchaseOrdersIdRoute,
  AppPurchaseOrdersNewRoute: AppPurchaseOrdersNewRoute,
  AppReportsBalanceSheetRoute: AppReportsBalanceSheetRoute,
  AppReportsBudgetReportRoute: AppReportsBudgetReportRoute,
  AppReportsProfitAndLossRoute: AppReportsProfitAndLossRoute,
  AppSalesOrdersIdRoute: AppSalesOrdersIdRoute,
  AppSalesOrdersNewRoute: AppSalesOrdersNewRoute,
  AppUsersNewRoute: AppUsersNewRoute,
  AppAnalyticalsIndexRoute: AppAnalyticalsIndexRoute,
  AppBillsIndexRoute: AppBillsIndexRoute,
  AppBrandsIndexRoute: AppBrandsIndexRoute,
  AppBudgetsIndexRoute: AppBudgetsIndexRoute,
  AppCategoriesIndexRoute: AppCategoriesIndexRoute,
  AppChartOfAccountsIndexRoute: AppChartOfAccountsIndexRoute,
  AppContactsIndexRoute: AppContactsIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppJournalEntriesIndexRoute: AppJournalEntriesIndexRoute,
  AppJournalsIndexRoute: AppJournalsIndexRoute,
  AppPaymentsIndexRoute: AppPaymentsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppPurchaseOrdersIndexRoute: AppPurchaseOrdersIndexRoute,
  AppSalesOrdersIndexRoute: AppSalesOrdersIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
  AppBillsIdPayRoute: AppBillsIdPayRoute,
  AppInvoicesIdPayRoute: AppInvoicesIdPayRoute,
  AppBillsIdIndexRoute: AppBillsIdIndexRoute,
  AppInvoicesIdIndexRoute: AppInvoicesIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
